spring:
  application:
    name: Comment-service
  cloud:
    config:
      uri: https://eurekat-257122.appspot.com
    discovery:
      client:
        simple:
          local:
            uri: http://eurekat-257122.appspot.com
eureka:
  client:
    serviceUrl:
      defaultZone: https://eureka-server-258207.appspot.com/eureka
      
