spring:
  application:
    name: reservation
  profiles:
    active: default
  cloud:
    config:
      enabled: true

eureka:
  instance:
    preferIpAddress: true
  client:
    registerWithEureka: true
    fetchRegistry: true
    serviceUrl:
      defaultZone: http://localhost:8080/eureka/

server:
  port: 8081
